name: Bev Isla
favicon: null
layout_spectrum: 0.5767822447232902
typography_spectrum: 0.5116340580862015
title: Bev Isla
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#090909'
    - '#2d302f'
    - '#53595e'
    - '#b6c0c4'
    - '#fdd1b7'
  brandStrength: 0.6875
  lightness: 0.8232822876889259
  saturation: 0.8125
  rhythmicContrast: 0.5551714138127863
purpose: []
